### ISSUE TITLE
touch navigation broken on firefox 64

### ISSUE THREAD

**Issue by joedf** [openseadragon/openseadragon#1579]
In Firefox v64, touch swiping still works, but as soon I try pinch-to-zoom. It breaks all navigation. The test device is touchscreen laptop. In Chrome v71.0.3578.98, no issues whatsoever...

**Comment by joedf** [comment]
Definitely the MouseTracker Module! Whoops! My bad, forgot to attach the exception:
```
TypeError: delegate.pinchGPoints[1] is undefined			mousetracker.js:2844:20
updatePointersDown			mousetracker.js:2844:20
onPointerDown				mousetracker.js:2366:13
pointerdown				mousetracker.js:234:56
TypeError: delegate.pinchGPoints[1] is undefined			mousetracker.js:3280:16
updatePointersMove			mousetracker.js:3280:16
handlePointerMove			mousetracker.js:2464:8
onPointerMoveCaptured			mousetracker.js:2442:12
pointermovecaptured			mousetracker.js:243:56
TypeError: delegate.pinchGPoints[1] is undefined			mousetracker.js:2844:20
updatePointersDown			mousetracker.js:2844:20
onPointerDown				mousetracker.js:2366:13
pointerdown				mousetracker.js:234:56
TypeError: delegate.pinchGPoints[1] is undefined			mousetracker.js:3100:28
updatePointersUp			mousetracker.js:3100:28
handlePointerUp				mousetracker.js:2417:13
onPointerUpCaptured			mousetracker.js:2396:12
pointerupcaptured			mousetracker.js:242:56
```
I'll take another jab at it Monday 👍

**Comment by msalsbery** [comment]
What? I don't remember a variable or property called "pinchGPoints"! ;)

Thanks @joedf !

**Comment by joedf** [comment]
Here's the function (I am using the source from sourcemaps on top of the "build" version):
```
    /**
     * Call when pointer(s) change coordinates, button state, pressure, tilt, or contact geometry (e.g. width and height)
     *
     * @function
     * @private
     * @inner
     * @param {OpenSeadragon.MouseTracker} tracker
     *     A reference to the MouseTracker instance.
     * @param {Object} event
     *     A reference to the originating DOM event.
     * @param {Array.<OpenSeadragon.MouseTracker.GesturePoint>} gPoints
     *      Gesture points associated with the event.
     */
    function updatePointersMove( tracker, event, gPoints ) {
        var delegate = THIS[ tracker.hash ],
            pointsList = tracker.getActivePointersListByType( gPoints[ 0 ].type ),
            i,
            gPointCount = gPoints.length,
            curGPoint,
            updateGPoint,
            gPointArray,
            delta,
            propagate;

        if ( typeof event.buttons !== 'undefined' ) {
            pointsList.buttons = event.buttons;
        }

        for ( i = 0; i < gPointCount; i++ ) {
            curGPoint = gPoints[ i ];
            updateGPoint = pointsList.getById( curGPoint.id );

            if ( updateGPoint ) {
                // Already tracking the pointer...update it
                if ( curGPoint.hasOwnProperty( 'isPrimary' ) ) {
                    updateGPoint.isPrimary = curGPoint.isPrimary;
                }
                updateGPoint.lastPos = updateGPoint.currentPos;
                updateGPoint.lastTime = updateGPoint.currentTime;
                updateGPoint.currentPos = curGPoint.currentPos;
                updateGPoint.currentTime = curGPoint.currentTime;
            } else {
                // Initialize for tracking and add to the tracking list (no pointerover or pointerdown event occurred before this)
                curGPoint.captured = false;
                curGPoint.insideElementPressed = false;
                curGPoint.insideElement = true;
                startTrackingPointer( pointsList, curGPoint );
            }
        }

        // Stop (mouse only)
        if ( tracker.stopHandler && gPoints[ 0 ].type === 'mouse' ) {
            clearTimeout( tracker.stopTimeOut );
            tracker.stopTimeOut = setTimeout( function() {
                handlePointerStop( tracker, event, gPoints[ 0 ].type );
            }, tracker.stopDelay );
        }

        if ( pointsList.contacts === 0 ) {
            // Move (no contacts: hovering mouse or other hover-capable device)
            if ( tracker.moveHandler ) {
                propagate = tracker.moveHandler(
                    {
                        eventSource:          tracker,
                        pointerType:          gPoints[ 0 ].type,
                        position:             getPointRelativeToAbsolute( gPoints[ 0 ].currentPos, tracker.element ),
                        buttons:              pointsList.buttons,
                        isTouchEvent:         gPoints[ 0 ].type === 'touch',
                        originalEvent:        event,
                        preventDefaultAction: false,
                        userData:             tracker.userData
                    }
                );
                if ( propagate === false ) {
                    $.cancelEvent( event );
                }
            }
        } else if ( pointsList.contacts === 1 ) {
            // Move (1 contact)
            if ( tracker.moveHandler ) {
                updateGPoint = pointsList.asArray()[ 0 ];
                propagate = tracker.moveHandler(
                    {
                        eventSource:          tracker,
                        pointerType:          updateGPoint.type,
                        position:             getPointRelativeToAbsolute( updateGPoint.currentPos, tracker.element ),
                        buttons:              pointsList.buttons,
                        isTouchEvent:         updateGPoint.type === 'touch',
                        originalEvent:        event,
                        preventDefaultAction: false,
                        userData:             tracker.userData
                    }
                );
                if ( propagate === false ) {
                    $.cancelEvent( event );
                }
            }

            // Drag
            if ( tracker.dragHandler ) {
                updateGPoint = pointsList.asArray()[ 0 ];
                delta = updateGPoint.currentPos.minus( updateGPoint.lastPos );
                propagate = tracker.dragHandler(
                    {
                        eventSource:          tracker,
                        pointerType:          updateGPoint.type,
                        position:             getPointRelativeToAbsolute( updateGPoint.currentPos, tracker.element ),
                        buttons:              pointsList.buttons,
                        delta:                delta,
                        speed:                updateGPoint.speed,
                        direction:            updateGPoint.direction,
                        shift:                event.shiftKey,
                        isTouchEvent:         updateGPoint.type === 'touch',
                        originalEvent:        event,
                        preventDefaultAction: false,
                        userData:             tracker.userData
                    }
                );
                if ( propagate === false ) {
                    $.cancelEvent( event );
                }
            }
        } else if ( pointsList.contacts === 2 ) {
            // Move (2 contacts, use center)
            if ( tracker.moveHandler ) {
                gPointArray = pointsList.asArray();
                propagate = tracker.moveHandler(
                    {
                        eventSource:          tracker,
                        pointerType:          gPointArray[ 0 ].type,
                        position:             getPointRelativeToAbsolute( getCenterPoint( gPointArray[ 0 ].currentPos, gPointArray[ 1 ].currentPos ), tracker.element ),
                        buttons:              pointsList.buttons,
                        isTouchEvent:         gPointArray[ 0 ].type === 'touch',
                        originalEvent:        event,
                        preventDefaultAction: false,
                        userData:             tracker.userData
                    }
                );
                if ( propagate === false ) {
                    $.cancelEvent( event );
                }
            }

            // Pinch
            if ( tracker.pinchHandler && gPoints[ 0 ].type === 'touch' ) {
                delta = delegate.pinchGPoints[ 0 ].currentPos.distanceTo( delegate.pinchGPoints[ 1 ].currentPos );
                if ( delta != delegate.currentPinchDist ) {
                    delegate.lastPinchDist = delegate.currentPinchDist;
                    delegate.currentPinchDist = delta;
                    delegate.lastPinchCenter = delegate.currentPinchCenter;
                    delegate.currentPinchCenter = getCenterPoint( delegate.pinchGPoints[ 0 ].currentPos, delegate.pinchGPoints[ 1 ].currentPos );
                    propagate = tracker.pinchHandler(
                        {
                            eventSource:          tracker,
                            pointerType:          'touch',
                            gesturePoints:        delegate.pinchGPoints,
                            lastCenter:           getPointRelativeToAbsolute( delegate.lastPinchCenter, tracker.element ),
                            center:               getPointRelativeToAbsolute( delegate.currentPinchCenter, tracker.element ),
                            lastDistance:         delegate.lastPinchDist,
                            distance:             delegate.currentPinchDist,
                            shift:                event.shiftKey,
                            originalEvent:        event,
                            preventDefaultAction: false,
                            userData:             tracker.userData
                        }
                    );
                    if ( propagate === false ) {
                        $.cancelEvent( event );
                    }
                }
            }
        }
    }

**Comment by Sachien** [comment]
Same issue can be observed in Firefox v60.5.1 with Openseadragon v2.4.0 and v2.3.0 as well.
@msalsbery any update on this issue?

**Comment by arnocertic** [comment]
Hi, same effects with Firefox 65.0.2 (64 bits) on Windows 10 touchscreen laptop.
No problem using the touchpad for zooming.
One try with pinch-to-zoom and everything is broken for touchscreen.

Everything is ok under Chrome 73.0.03683.75 or IE 11

**Comment by iangilman** [comment]
Looks like @msalsbery has gotten distracted by other things. Is anyone else up for looking into this?

**Comment by msalsbery** [comment]
Sorry sorry sorry!! Have started to look into it then hammered by work projects. Seems simple but variations between browser event handling makes it mind-boggling at the very least ;) I’m always appreciative of any help, comments, suggestions, insults however...

Good news about Edge browser moving to chromium engine...the only browser with a good pointer event model implementation will now be broken as well ;)

**Comment by gmlnchv** [comment]
Hi @msalsbery, any progress on this? Running into this issue (on a fairly old chrome version though, via a BrightSign device).

**Comment by msalsbery** [comment]
@gmlnchv

Patch in progress, very soon!

**Comment by gmlnchv** [comment]
Thanks @msalsbery! Out of curiosity, do you think it's got anything to do with #1534 at all? Similar symptoms...

**Comment by msalsbery** [comment]
@gmlnchv I hadn’t seen #1534, I’ll look into it thanks!

**Comment by joedf** [comment]
I don't know if this has been fixed, but I have been using Hammer.js to get around this issue. :+1:

**Comment by joedf** [comment]
@msalsbery Okay, I have tested v2.4.2 and v2.5 (preview) side-by-side. Both seem to be working now in Firefox 79.0 x64 on Windows 10 Pro v1909 (18363.1016). However, v2.5 throws this error on every touch event I do. Also, there seems to be some "zoom-clipping"; the zoom level will sometimes jump to a higher zoom or lower zoom.

```
Uncaught DOMException: Invalid pointer id. openseadragon.js:739
    f mousetracker.js:1678
    W mousetracker.js:3033
    A mousetracker.js:2974
    pointerup mousetracker.js:256
    (Async: EventListener.handleEvent)
    addEvent openseadragon.js:2095
    setTracking mousetracker.js:1539
    setTracking mousetracker.js:339
    MouseTracker mousetracker.js:293
    Viewer viewer.js:283
    OpenSeadragon openseadragon.js:740
    <anonymous> index_v2.5.html:10
```

**Comment by msalsbery** [comment]
> Okay, I have tested v2.4.2 and v2.5 (preview) side-by-side

@joedf  GREAT info, thank you!

If you get a minute, could you please do me a huge favor and go to [this site](https://openseadragon-imaging.github.io/#/imaginghelper) and copy the navigator, osdBrowser, and osdMouseTracker objects from the properties pane and paste them here? It should look like this:
```
navigator: {
  "appVersion": "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36 Edg/84.0.522.63",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36 Edg/84.0.522.63"
}
osdBrowser: {
  "vendor": "Chromium Edge",
  "version": 84,
  "alpha": true,
  "opacity": true
}
osdMouseTracker: {
  "wheelEventName": "wheel",
  "havePointerCapture": true,
  "havePointerEvents": true,
  "unprefixedPointerEvents": true,
  "havePointerOverOut": true
}
```
I want to make sure they're sane values, and it'll help me debug since I don't have a desktop touch device I can test on at the moment. Thanks again!

**Comment by joedf** [comment]
Sure, no worries!
````
navigator: {
  "appVersion": "5.0 (Windows)",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"
}

osdBrowser: {
  "vendor": "Firefox",
  "version": 79,
  "alpha": true,
  "opacity": true
}

osdMouseTracker: {
  "wheelEventName": "wheel",
  "havePointerCapture": true,
  "havePointerEvents": true,
  "unprefixedPointerEvents": true,
  "havePointerOverOut": true
}
```

**Comment by msalsbery** [comment]
@joedf  Perfect, thank you!

**Comment by msalsbery** [comment]
@joedf 

I've [posted new builds](https://github.com/openseadragon/openseadragon/pull/1872#issuecomment-673608460)...should fix the exception you were seeing.

If you get a chance to test on Firefox desktop touch, can you please let me know if you see any console warnings? If there's _'releasePointerCapture() called on invalid pointer ID'_ warnings then it's a Firefox bug and I'll suppress the warning. Hopefully there's no warnings and it was my bug and it works

**Comment by joedf** [comment]
@msalsbery Okay, so it seems the error is still being throw in firefox on my touch laptop.
`releasePointerCapture() called on invalid pointer ID ............................. mousetracker.js:1701:30`
I tested it in chromium-edge and it worked flawlessly, no warnings or errors. It seemed more responsive and smoother. In firefox, I've noticed there's the touch left-click (context-menu) square that shows up when holding the touched slightly longer, whereas in edge, there's was none of that.

Firefox:
![image](https://user-images.githubusercontent.com/3848219/91206690-8a3e9080-e6d5-11ea-819f-f532f9ebc53b.png)
![image](https://user-images.githubusercontent.com/3848219/91206703-8f034480-e6d5-11ea-99fd-c51a48b098f2.png)

Edge (chromium):
![image](https://user-images.githubusercontent.com/3848219/91206738-9cb8ca00-e6d5-11ea-86fb-5bb6f7e7cd0f.png)

It looks like chromium is using a custom gui context-menu solution, whereas firefox is using the native Windows API menu (possibly indirectly).

**Comment by msalsbery** [comment]
> it seems the error is still being throw in firefox on my touch laptop

Just the console warning then? Does it work though since the exception that was occurring is now caught?

The context menu stuff should be fixable by css...I'm looking into that now to see if I can improve that on the OpenSeadragon end.

Thank you, it's great to get this feedback!

**Comment by msalsbery** [comment]
Hmm we don't even look at the contextmenu event anywhere in the code. I'm pretty sure I can fix that...well hopefully! ;-)

It's happening on a "long touch" gesture though, yes?

**Comment by msalsbery** [comment]
@joedf 

I've [posted new builds](https://github.com/openseadragon/openseadragon/pull/1872#issuecomment-673608460)...

Removed console warning
Added contextmenu handling

**Comment by joedf** [comment]
@msalsbery nono, non-fatal errors only, it all works ok. Sounds good. I'll give it a try tomorrow morning 👍

**Comment by joedf** [comment]
Works great, no warnings. Yes, a long press. 

I'm not sure, but it seems it will jump depending on how fast I put two fingers when I release or touch the screen, I so call "Zoom clipping". None of that in Edge. I'm not sure this can be fixed, possibly mitigated but perhaps not worth it to fix without being able to reproduce it. It seems firefox has been generally somewhat quirky for touch events. I've used hammerjs in the past to mitigated issues, but that's not optimal.

**Comment by msalsbery** [comment]
@joedf 

Is the long press issue ok now? I only tested with mouse right-click on desktop and touch on Webkit (iOS).

I'm bummed Firefox is quirky...they used to be the good one ;-)  On Webkit there's a little jump with touch/pinch but I think it's the combination of a few pixelsmovement at initial touch with a fat target (finger) and (perhaps even more so) the lack of the spring animation on the pinch gesture which can feel really quick compared to the lag of the spring animation.

Thanks much!!

**Comment by joedf** [comment]
@msalsbery Yes, the long press issue, but I wouldn't worry about it too much if there are other priorities.

Yes, I agree. I've been using Firefox since Netscape was no longer an option... Despite the quirks, I still use Firefox as my main as a matter of principle. From a technical perspective, Edge-Chromium seems promising. 

And thanks to you for looking into this matter! 👍

**Comment by msalsbery** [comment]
> Yes, the long press issue, it works, but minor jumps like you've explained

But does the long press still bring up the undesired context box or menu? If so, I may need to mess with style/css - I'm already about to, going to add `-webkit-touch-callout: none` and  `*-user-select: none` styles...

I was already a big Edge fan, and I LOVE that they went with Chromium - mainly because it eliminated a bunch of inconsistencies with pointer events. I know front-end devs have seemed to like Chrome for a long time, but ironically I didn't really like it until fairly recently. Now days, it's Firefox that's giving me grief the most (and Webkit/iOS, but that'll never change haha)

**Comment by joedf** [comment]
Well actually the contextmenu itself wasn't really issue. I noticed now it wont even show anymore. It was fine before, I was just thinking that the long-press square was the issue. Not sure that's intended, and perhaps my bad. 👶

**Comment by msalsbery** [comment]
@joedf 

Oh ok, cool.

I don't _think_ a default context menu on the viewer is desirable in most cases, so I removed it and added a viewer event for the ability to add a custom context menu. @iangilman may reject that in code review, however...we'll see ;-)

**Comment by joedf** [comment]
Ahh okay understood. 👍

**Comment by iangilman** [comment]
Yeah, I think we shouldn't suppress the context menu, actually. For many scenarios, being able to save the current state of the viewer (which is one of the options on the context menu) is a desirable feature.

**Comment by msalsbery** [comment]
@iangilman roger that, I’ll flip the default action (the change is in #1872). Thanks!

**Comment by msalsbery** [comment]
Context menu now enabled by default in MouseTracker (#1872)

**Comment by msalsbery** [comment]
@joedf 

[Builds and demo sites here](https://github.com/openseadragon/openseadragon/pull/1872#issuecomment-673608460)

**Comment by joedf** [comment]
@msalsbery Okay, I can confirm that navigation is not broken with touch event on firefox 86, so we can close this. 

Though, when a finger is on the screen for more than 1-2s (the approx. time for the context menu to normally show up) the windows 10 animated square shows up (quirky, but okay and non-breaking) but no context menu (as expected, good) but the positioning will jump a little. Meanwhile, no quirkness, position jumps or animated square shows in chrome at all giving it a smoother feel than firefox. That said, I believe this is now a separate issue.

**Comment by msalsbery** [comment]
@joedf  great thank you for checking!!
