### ISSUE TITLE
setImageSmoothingEnabled ignored when useSketch is true

### ISSUE THREAD

**Issue by yellowtailfan** [openseadragon/openseadragon#1646]
I found some situations where image smoothing was being applied at high zoom when viewing multiple images, even though I have set the following optons when initialising the OSD Viewer:
```
        imageSmoothingEnabled: false,
        smoothTileEdgesMinZoom: Infinity,
```
 I am using opacity to switch rapidly between multiple tileSources, by adapting a [Codepen recipe on image fading](https://codepen.io/iangilman/pen/YXRLea) by @iangilman. 

The fault is intermittent, and occurs around 20x - 40x zoom on images around  3000x2000 pixels in size. The first image always has nearest-neighbour (NN) interpolation (image smoothing off), as intended. But sometimes the second image has bi-linear (BL) interpolation (image smoothing on). Occasionally, zooming or panning the second image was causing the interpolation to switch between NN and BL.

I think my use of multiple images and opacity together with certain zoom or pan conditions is triggering the useSketch flag inside drawer.js, which then creates a new context. The new context is missing the image smoothing settings.

I am about to submit a pull request which fixes this issue in my testing.

**Comment by yellowtailfan** [comment]
Related to #1028 and #1593.

**Comment by yellowtailfan** [comment]
I just realised I am using viaWebGL in the script that displayed this bug. There may be an interaction between this behaviour and viaWebGL, so I will test it without viaWebGL and report back here.

**Comment by yellowtailfan** [comment]
I am using #1647 and it has resolved the bug for 2 images with size around 3000x2000. But I have now seen the bug intermittently in another situation where the first image is 100x100 and the second image is about 2000x1300.

**Comment by iangilman** [comment]
Thank you for tracking this down! I've merged #1647, but let me know if you figure out what's causing the remaining issue.

**Comment by yellowtailfan** [comment]
I've confirmed using the code before #1647 was applied that the bug described at the top of this issue still occurs when viaWebGL is disabled.

I've also found a new reproducible bug, using OSD with #1647 applied:
1. Open 2 images with size about 2500x1750
2. Switch to second image
3. Zoom in to about 10x
4. Resize the browser window

After resizing the browser window, the second image has image smoothing applied.
