### ISSUE TITLE
Custom Zoom Buttons – destroy() not fully removing them

### ISSUE THREAD

**Issue by mattwolff** [openseadragon/openseadragon#1908]
I've got custom elements set for my `zoomInButton` and `zoomOutButton`: 

```
OpenSeadragon({
   ...
   zoomInButton:  "zoomInDiv",
   zoomOutButton: "zoomOutDiv",
   ...
});
```
After destroying a Viewer and subsequently creating a new one, these zoom buttons still work but also log the following errors to the console:
– `Cannot set property 'lastZoomTime' of undefined`
– `Cannot set property 'zooming' of undefined`

Screenshot of the console included as well:
<img width="1036" alt="Screen Shot 2020-11-20 at 7 32 05 PM" src="https://user-images.githubusercontent.com/21694984/99862297-265a2580-2b67-11eb-9b0e-153819dc320f.png">

_Originally posted by @mattwolff in https://github.com/openseadragon/openseadragon/issues/1878#issuecomment-731474734_

**Comment by msalsbery** [comment]
@mattwolff  Thank you for reporting this!

If you have a few minutes to spare, I have a large patch for MouseTracker in the works...could you maybe try [the OpenSeadragon preview build here](https://github.com/openseadragon/openseadragon/pull/1872#issuecomment-673608460) and see if the issue is still there?

Regardless, I will investigate this further...

**Comment by msalsbery** [comment]
@mattwolff 

Now that #1884 is merged in I'm curious if it resolved your issue as well... 

[Latest builds from master branch here](https://github.com/openseadragon/openseadragon/pull/1872#issuecomment-673608460) if you'd like to test it out...

**Comment by mattwolff** [comment]
Yes! Just tested it out and this is no longer an issue – amazing overhaul.

**Comment by msalsbery** [comment]
> Yes, just tested it out and this is no longer an issue – amazing overhaul.

Awesome, thank you for checking!

**Comment by mattwolff** [comment]
Resolved by #1884

**Comment by cactusjosh** [comment]
Hate to be the bearer of bad vibes but I still have this issue. My local version of openseadragon is the latest. I am using OSD with react and have two zoom in/out buttons built in react. Any ideas without posting a code sample?

**Comment by iangilman** [comment]
@cactusjosh when you say the latest, do you mean the most recent release, or did you build from the repository master branch? This change hasn't been released yet, but it is on master.
