### ISSUE TITLE
Is zoomify still working?

### ISSUE THREAD

**Issue by lucasgueller** [openseadragon/openseadragon#2177]
I tried to use zoomify to create the tiles, but it didn't work on the code. I tried to do like this example http://openseadragon.github.io/examples/tilesource-zoomify/, but the image does not show on the page, only the navigator does. Am I doing something wrong? (I'm a noob) or the openseadragon isn't working with zoomify?

**Comment by iangilman** [comment]
It should be working! Can you share a link to your project, or at least the code for the tile source? Also, are you seeing any errors in the console?

**Comment by lucasgueller** [comment]
it's working, sorry, I was not seeing what was wrong till today. But, I still have a question. I want to do something like Google maps but with images of old city maps. is there some plugin on OSD that I can put markers on specific areas that only show if the viewer click on this areas (like the markers on Google maps)? After the click, a pop-up shows up with a link or something

**Comment by iangilman** [comment]
@lucasgueller As far as I'm aware, there is nothing that does all of that for OSD. If you want to build it yourself, you'll want to add some overlays to your image and when the user clicks on them, you can update some sort of pop-up. You should be able to do all of that with vanilla OSD, but you might find some of these plugins useful:

https://openseadragon.github.io/#plugins

You can also take a look at these recipes: 

https://codepen.io/collection/APoyjJ

If you want something that's more map-oriented out of the box, you might consider trying https://leafletjs.com/ instead of OSD.
