### ISSUE TITLE
`canvas-drag-end` firing only sporadically on Google Chrome

### ISSUE THREAD

**Issue by acdamiani** [openseadragon/openseadragon#2836]
I'm working on a Macbook Air M2. On Chromium-based browsers (tested with Google Chrome and [Helium](https://helium.computer/)), the `canvas-drag-end` event fires only occasionally. I was not able to determine the conditions for its firing; it seems random. One consequence of this issue is that view correction via `viewport.applyConstraints` and the flick gesture don't work consistently. Firefox and Safari seem to work properly. Here's the config I used:

```ts
const viewer = OpenSeadragon({
  element: el,
  crossOriginPolicy: "Anonymous",
  tileSources: [
    {
      "@context": "http://iiif.io/api/image/2/context.json",
      "@id": "https://libimages1.princeton.edu/loris/pudl0001%2F4609321%2Fs42%2F00000001.jp2",
      width: 5233,
      height: 7200,
      profile: ["http://iiif.io/api/image/2/level2.json"],
      protocol: "http://iiif.io/api/image",
      tiles: [
        {
          scaleFactors: [0.5, 1, 2, 4, 8, 16, 32],
          width: 1024
        }
      ]
    }
  ]
});

viewer.addHandler("canvas-press", () => (cursor = "grabbing"));
// this event always fires...
viewer.addHandler("canvas-release", () => (cursor = "grab"));

const viewport = viewer.viewport;
viewer.addHandler("canvas-drag", (e) => {
  e.preventDefaultAction = true;
  viewport.panBy(viewport.deltaPointsFromPixels(e.delta.negate()), true);
});

// ...this event doesn't
viewer.addHandler("canvas-drag-end", (e) => {
  e.preventDefaultAction = true;
  
  const x = 0.25 * e.speed * Math.cos(e.direction);
  const y = 0.25 * e.speed * Math.sin(e.direction);
  const center = viewport.pixelFromPoint(viewport.getCenter(true));
  const target = viewport.pointFromPixel(new OpenSeadragon.Point(center.x - x, center.y - y));
  viewport.panTo(target, false);

  viewport.applyConstraints();
});
```

https://github.com/user-attachments/assets/56d4de48-c153-4398-99cc-9ae2c6d37415

**Comment by iangilman** [comment]
Strange! It certainly seems like it should be working.

Here's where that event gets fired: 

https://github.com/openseadragon/openseadragon/blob/fbb7dfba9aaa8fbe15b7760774f57348f9d77d4c/src/mousetracker.js#L3432

I poked around a bit and I couldn't see any obvious culprits.

If you'd like to investigate further, I'm happy to give you pointers. Otherwise, hopefully someone else will take an interest.

If you just want to hack around it, I suppose you could use the `canvas-release` event.

**Comment by msalsbery** [comment]
@acdamiani 

Is this using a mouse device? If so, what happens if you just do this (note the gesture settings I added to the viewer):
```ts
const viewer = OpenSeadragon({
  element: el,
  crossOriginPolicy: "Anonymous",
  tileSources: [
    {
      "@context": "http://iiif.io/api/image/2/context.json",
      "@id": "https://libimages1.princeton.edu/loris/pudl0001%2F4609321%2Fs42%2F00000001.jp2",
      width: 5233,
      height: 7200,
      profile: ["http://iiif.io/api/image/2/level2.json"],
      protocol: "http://iiif.io/api/image",
      tiles: [
        {
          scaleFactors: [0.5, 1, 2, 4, 8, 16, 32],
          width: 1024
        }
      ]
    }
  ],
  gestureSettingsMouse: {
    flickEnabled: true,
  },
});

viewer.addHandler("canvas-press", () => (cursor = "grabbing"));
viewer.addHandler("canvas-release", () => (cursor = "grab"));
```
Also, is this in a React component?

**Comment by acdamiani** [comment]
Including `flickEnabled: true` doesn't seem to fix it. (This is in a Svelte component.)

You can see this issue with a few OpenSeadragon wrappers; for example, [Mirador](https://projectmirador.org/demo/) and [TIFY](https://tify.rocks) both allow you pan off the screen with enough fiddling. I was not able to reproduce this behavior on Firefox. I'm going to look into doing some sort of hack with `canvas-release` per @iangilman's comment. I'll just track `delta` myself and prevent default pan behavior.

| Mirador | TIFY |
| ---- | ---- |
| <img width="701" height="885" alt="Image" src="https://github.com/user-attachments/assets/8864c4c0-16b8-4efd-b6e7-f154b6e324f1" /> | <img width="1470" height="885" alt="Image" src="https://github.com/user-attachments/assets/820a3d1b-3638-4527-8bcc-40de95f37d29" /> |

**Comment by msalsbery** [comment]
> Including `flickEnabled: true` doesn't seem to fix it. (This is in a Svelte component.)

@acdamiani  

My main point was more about using the built-in flick handling (ie remove your 'canvas-drag' and 'canvas-drag=end' handlers) just to eliminate any possible unseen issues.

I have tried your code and the default library code and I still can't reproduce on any device I have access to... 🤷
