### ISSUE TITLE
Binding Custom Buttons example not working?

### ISSUE THREAD

**Issue by mdjasper** [openseadragon/openseadragon#317]
It appears that the example, "Binding Custom Buttons" is not working. (http://openseadragon.github.io/examples/ui-binding-custom-buttons/). When clicking "next" or "previous", the callback function onPageChange is never called, and the "page N of 3" does not update.

I see the callback function declared, but how is this function bound to a new action, which is then bound to an html element id?

In the meantime, I've resorted to using a onClick handler for the button externally, and referencing my own callback function that exists in the same scope as the OpenSeaDragon object. This works, but is obviously not the OpenSeaDragon way.

**Comment by rajahassan-08** [comment]
I have used 
  const handleNextImage = () => {
    if (viewerRef.current && viewerRef.current.world.getItemCount() > 0) {
      const nextPage = Math.min(viewerRef.current.currentPage() + 1 );
      viewerRef.current.goToPage(nextPage);
    }
  };
  
  const handlePreviousImage = () => {
    if (viewerRef.current && viewerRef.current.world.getItemCount() > 0) {
      const prevPage = Math.max(viewerRef.current.currentPage() - 1, 0);
      viewerRef.current.goToPage(prevPage);
    }
  };
  these function on click event and its working, is there any drawback for this

**Comment by iangilman** [comment]
Looks good to me!

**Comment by rajahassan-08** [comment]
> Looks good to me!

But when switching to full screen mode its not working

**Comment by iangilman** [comment]
What's not working in fullscreen? How are you triggering these functions? Are they attached to buttons on the screen?

**Comment by rajahassan-08** [comment]
I implemented custom buttons for switching next and previous images with the function i have mentioned above, in full screen mode it was not working, they were not attathched by id which mentioned in the osd documentation

**Comment by iangilman** [comment]
When you go into fullscreen can you still see those buttons?

At any rate, for historical reasons there's a bunch of stuff that happens when going into fullscreen. You can read more about that here: https://github.com/openseadragon/openseadragon/issues/2205

Short term, the solution might be to watch for the fullscreen event and re-add the event handler to the buttons.
